import { SmaliPatch } from './types'

/** `return void;` in Smali. */
const RETURN_VOID_SMALI = ['.locals 0', 'return-void']

/** `return true;` in Smali. */
const RETURN_TRUE_SMALI = ['.locals 1', 'const/4 v0, 0x1', 'return v0']

/** `return new java.security.cert.X509Certificate[] {};` in Smali. */
const RETURN_EMPTY_CERT_ARRAY_SMALI = [
  '.locals 1',
  'const/4 v0, 0x0',
  'new-array v0, v0, [Ljava/security/cert/X509Certificate;',
  'return-object v0',
]

const RETURN_EMAIL_SMALI = [
  '.locals 1',
  'const-string v0, "infinity@nowhere.com"',
  'return-object v0',
]

const RETURN_COGNITO_CONSTRUCTOR_SMALI = [
    '.locals 2',
    'invoke-direct {p0}, Ljava/lang/Object;-><init>()V',
    'iput-object p1, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->h:Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool;',
    'iput-object p7, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->a:Landroid/content/Context;',
    'const-string v1, "infinity@nowhere.com"',
    'iput-object v1, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->e:Ljava/lang/String;',
    'iput-object p6, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->b:Lcom/amazonaws/services/cognitoidentityprovider/AmazonCognitoIdentityProvider;',
    'const-string v1, "1i2fo3hm4d5m6bf789vj01q2ea"',
    'iput-object v1, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->c:Ljava/lang/String;',
    'iput-object p4, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->d:Ljava/lang/String;',
    'iput-object p5, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->i:Ljava/lang/String;',
    'const/4 p1, 0x0',
    'iput-object p1, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->g:Ljava/lang/String;',
    'iput-object p1, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->j:Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;',
    'return-void',
]

const RETURN_COGNITO_GETSESSION_SMALI = [
    '.locals 5',
    'invoke-virtual {p0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->l()V',
    'monitor-enter p0',
    ':try_start_0',
    'iget-object v0, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->e:Ljava/lang/String;',
    'if-nez v0, :cond_0',
    'const-string v0, "123456789012345678901"',
    'iput-object v0, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->e:Ljava/lang/String;',
    ':cond_0',
    'iget-object v0, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->j:Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;',
    'if-eqz v0, :cond_2',
    'invoke-virtual {v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;->b()Z',
    'move-result v1',
    'if-eqz v1, :cond_1',
    'monitor-exit p0',
    ':try_end_0',
    '.catchall {:try_start_0 .. :try_end_0} :catchall_0',
    'return-object v0',
    ':cond_1',
    ':try_start_1',
    'new-instance v1, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoIdToken;',
    'const-string v2, "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTIzNDU2Ny1jZDEyLTEyZGEtMTIzNC1lYWYxZTJiYTM0NTYiLCJpc3MiOiJodHRwczovL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tL3VzLWVhc3QtMV96RURmWEJ6NGIiLCJhdWQiOiIxaTJmbzNobTRkNW02YmY3ODl2ajAxcTJlYSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNzgyODY0MDAwLjAsImlhdCI6MTc4Mjg2NDAwMC4wLCJleHAiOjIyMjQ3MTM2MDAuMCwianRpIjoiZjZiMGNjZTUtZjc3Ny00NmU5LThkZTAtN2VhNzllYjY1NDYwIiwib3JpZ2luX2p0aSI6IjEyZTNhNGI1LWJlNjctODlmMC1iMWIyLTNiZjQ1NmI3ODkwMSIsImV2ZW50X2lkIjoiMTJkMzRhYjUtNjc4OS0wMTJhLWJiYzMtNDVjNmY3ZmQ4Y2Y5IiwiY29nbml0bzpncm91cHMiOlsiRlJFRVVTRVIiXSwiY29nbml0bzpyb2xlcyI6WyJhcm46YXdzOmlhbTo6MzkxOTU5MjE4MjU3OnJvbGUvQW1hem9uRVNDb2duaXRvQWNjZXNzIl0sImNvZ25pdG86dXNlcm5hbWUiOiJiMTIzNDU2Ny1jZDEyLTEyZGEtMTIzNC1lYWYxZTJiYTM0NTYiLCJjdXN0b206cm9sZSI6IkZSRUVVU0VSIiwiZ2VuZGVyIjoiTWFsZSIsIm5pY2tuYW1lIjoiaW5maW5pdHkxMjM0NTY3IiwiZW1haWwiOiJpbmZpbml0eUBub3doZXJlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwic29jaWFsX2xvZ2luIjoibm8iLCJpZGVudGl0aWVzIjpbeyJ1c2VySWQiOiIxMjM0NTY3ODkwMTIzNDU2Nzg5MDEiLCJwcm92aWRlck5hbWUiOiJHb29nbGUiLCJwcm92aWRlclR5cGUiOiJHb29nbGUiLCJpc3N1ZXIiOm51bGwsInByaW1hcnkiOiJmYWxzZSIsImRhdGVDcmVhdGVkIjoiMTc3OTEyMTIyMTY2NyJ9XSwiY3VzdG9tOmdvb2dsZV9wcm9maWxlX3BpYyI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0lRUTZ4V3FIZTMwdGtBQkhsb1FFa1BQYy13SmJycmxWREdpRklzdEgwNWZBYz1zOTYtYyIsImN1c3RvbTpnb29nbGVfbmFtZSI6IkluZmluaXR5IiwiY3VzdG9tOmdvb2dsZV9saW5rZWQiOiJ5ZXMiLCJjdXN0b206bGlua2VkX2FjY291bnQiOiJ5ZXMiLCJjdXN0b206cHJpbWFyeV9hdHRyIjoiZW1haWwiLCJjdXN0b206c3FzX2FjY2VzcyI6IkFTSUFWV1FVWEJCWkk2WVFQSjU2IiwiY3VzdG9tOnNxc19zZWNyZXQiOiJuT21ZKzI3K1E2ZFlXVnJ5dXJTTXJEYU0reXJnNm85WkFWRGplNFFwIiwiY3VzdG9tOnNxc19leHBpcnkiOiIyMDI2LTA3LTMxIDEzOjIyOjAxIiwiY3VzdG9tOnNxc19zZXNzaW9uIjoiRndvR1pYSXZZWGR6RVBiLy8vLy8vLy93RWFERWMvZzdBa1p2dWpJMEFjSGlLdUFRY1RibVBWbzN6TDZzSGhLZ0U0dVdMTGZyZk84Y2pjT3ZDeUM0NXBoRTlUc0hhVGtMTjFqUFhPcGExdjM1Sm1LM2tWYjJ4NDFDbWM5YTNIa1h0aSBiOXJqOTRnbktydVB3NXlmV1ZqRWVUK09JRGRqS3ZzN1Q0SUZUMW5RVEhrK0VyL1h1R3lJTEtXKzBrSWlHSjgzczkzRUE3cHMrdlBwbWd2NmZSZE1pSFNZV0pwMkRrRWsrd3FCbUtSWGdUb2pWQ0sxR2E2YUd4cC9qUVdWVmZGWCsvZXZ3eEFZdWhTTENpU2hXVy9VeENqcHByTFRCakl0Ui9jY2d1WG1Ld1NYaHMrVjdza28wUk4xaTYzZ29aVlloUEYgQ2NFSExLTW5Pak1HZDBtQUNGZTI4WFJhUSIsImN1c3RvbTp2YWxpZGF0ZWRfZW1haWwiOiJpbmZpbml0eUBub3doZXJlLmNvbSJ9.7tD1tFB3jYCQLFuBmmWPUywD0xE8SznZ-2Tpy_9Udp4"',
    'invoke-direct {v1, v2}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoIdToken;-><init>(Ljava/lang/String;)V',
    'new-instance v2, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoAccessToken;',
    'const-string v3, "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTIzNDU2Ny1jZDEyLTEyZGEtMTIzNC1lYWYxZTJiYTM0NTYiLCJpc3MiOiJodHRwczovL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tL3VzLWVhc3QtMV96RURmWEJ6NGIiLCJjbGllbnRfaWQiOiIxaTJmbzNobTRkNW02YmY3ODl2ajAxcTJlYSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE3ODI4NjQwMDAuMCwiaWF0IjoxNzgyODY0MDAwLjAsImV4cCI6MjIyNDcxMzYwMC4wLCJqdGkiOiIxMmUzYTRiNS1iZTY3LTg5ZjAtYjFiMi0zYmY0NTZiNzg5MDEiLCJvcmlnaW5fanRpIjoiMTJlM2E0YjUtYmU2Ny04OWYwLWIxYjItM2JmNDU2Yjc4OTAxIiwiZXZlbnRfaWQiOiIxMmQzNGFiNS02Nzg5LTAxMmEtYmJjMy00NWM2ZjdmZDhjZjkiLCJjb2duaXRvOmdyb3VwcyI6WyJGUkVFVVNFUiJdLCJ1c2VybmFtZSI6ImIxMjM0NTY3LWNkMTItMTJkYS0xMjM0LWVhZjFlMmJhMzQ1NiIsImRldmljZV9rZXkiOiJ1cy1lYXN0LTFfZmUyYzVkZWItZDU2YS00NDdhLWE0Y2UtZWJlMTJjODc3MDIyIn0.z2hQc6P0ujiNVh06sH0AUpWwFX-WtrvrMit-ghcXQ24"',
    'invoke-direct {v2, v3}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoAccessToken;-><init>(Ljava/lang/String;)V',
    'new-instance v3, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoRefreshToken;',
    'const-string v4, "eyJjdHkiOiAiSldUIiwgImVuYyI6ICJBMjU2R0NNIiwgImFsZyI6ICJSU0EtT0FFUCJ9.D6GNnxL6WtzWtBXoKB3FSp346afTqWrkHVb5mmK_d-Q.kmuHe-8TPKAnS_fM.eyJzdWIiOiAiYjEyMzQ1NjctY2QxMi0xMmRhLTEyMzQtZWFmMWUyYmEzNDU2IiwgImNsaWVudF9pZCI6ICIxaTJmbzNobTRkNW02YmY3ODl2ajAxcTJlYSIsICJhdXRoX3RpbWUiOiAxNzgyODY0MDAwLjAsICJkZXZpY2Vfa2V5IjogInVzLWVhc3QtMV9mZTJjNWRlYi1kNTZhLTQ0N2EtYTRjZS1lYmUxMmM4NzcwMjIiLCAiaWF0IjogMTc4Mjg2NDAwMC4wLCAiZXhwIjogMjIyNDcxMzYwMC4wfQ.cd_1SRyTRsriwcyOMHjuNw"',
    'invoke-direct {v3, v4}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoRefreshToken;-><init>(Ljava/lang/String;)V',
    'new-instance v4, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;',
    'invoke-direct {v4, v1, v2, v3}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;-><init>(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoIdToken;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoAccessToken;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoRefreshToken;)V',
    'iput-object v4, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->j:Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;',
    'monitor-exit p0',
    ':try_end_1',
    '.catchall {:try_start_1 .. :try_end_1} :catchall_0',
    'return-object v4',
    ':cond_2',
    ':try_start_2',
    'invoke-virtual {p0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->C()Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;',
    'move-result-object v0',
    'invoke-virtual {v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;->b()Z',
    'move-result v1',
    'if-eqz v1, :cond_3',
    'iput-object v0, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->j:Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;',
    'monitor-exit p0',
    ':try_end_2',
    '.catchall {:try_start_2 .. :try_end_2} :catchall_0',
    'return-object v0',
    ':cond_3',
    ':try_start_3',
    'invoke-virtual {p0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->s()Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;',
    'move-result-object v0',
    ':try_end_3',
    '.catchall {:try_start_3 .. :try_end_3} :catchall_0',
    'monitor-exit p0',
    'return-object v0',
    ':catchall_0',
    'move-exception v0',
    'monitor-exit p0',
    'throw v0',
]

const RETURN_COGNITO_GETCACHEDSESSION_SMALI = [
    '.locals 9',
    ':try_start_0',
    'new-instance v0, Ljava/lang/StringBuilder;',
    'invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V',
    'const-string v1, "CognitoIdentityProvider."',
    'invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'iget-object v1, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->c:Ljava/lang/String;',
    'invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'const-string v1, "."',
    'invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'iget-object v2, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->e:Ljava/lang/String;',
    'invoke-virtual {v0, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'const-string v2, ".idToken"',
    'invoke-virtual {v0, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;',
    'move-result-object v0',
    'new-instance v2, Ljava/lang/StringBuilder;',
    'invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V',
    'invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'iget-object v3, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->c:Ljava/lang/String;',
    'invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'iget-object v3, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->e:Ljava/lang/String;',
    'invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'const-string v3, ".accessToken"',
    'invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;',
    'move-result-object v2',
    'new-instance v3, Ljava/lang/StringBuilder;',
    'invoke-direct {v3}, Ljava/lang/StringBuilder;-><init>()V',
    'invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'iget-object v1, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->c:Ljava/lang/String;',
    'invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'const-string v1, "."',
    'invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'iget-object v1, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->e:Ljava/lang/String;',
    'invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'const-string v1, ".refreshToken"',
    'invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;',
    'invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;',
    'move-result-object v1',
    'iget-object v3, p0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->h:Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool;',
    'iget-object v3, v3, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool;->j:Lcom/amazonaws/internal/keyvaluestore/AWSKeyValueStore;',
    'const/4 v4, 0x0',
    'move-object v5, v4',
    'move-object v6, v4',
    'move-object v7, v4',
    'invoke-virtual {v3, v0}, Lcom/amazonaws/internal/keyvaluestore/AWSKeyValueStore;->b(Ljava/lang/String;)Z',
    'move-result v8',
    'if-eqz v8, :cond_0',
    'invoke-virtual {v3, v0}, Lcom/amazonaws/internal/keyvaluestore/AWSKeyValueStore;->e(Ljava/lang/String;)Ljava/lang/String;',
    'move-result-object v8',
    'if-eqz v8, :cond_0',
    'new-instance v5, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoIdToken;',
    'invoke-direct {v5, v8}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoIdToken;-><init>(Ljava/lang/String;)V',
    'goto :goto_0',
    ':cond_0',
    'const-string v8, "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTIzNDU2Ny1jZDEyLTEyZGEtMTIzNC1lYWYxZTJiYTM0NTYiLCJpc3MiOiJodHRwczovL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tL3VzLWVhc3QtMV96RURmWEJ6NGIiLCJhdWQiOiIxaTJmbzNobTRkNW02YmY3ODl2ajAxcTJlYSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNzgyODY0MDAwLjAsImlhdCI6MTc4Mjg2NDAwMC4wLCJleHAiOjIyMjQ3MTM2MDAuMCwianRpIjoiZjZiMGNjZTUtZjc3Ny00NmU5LThkZTAtN2VhNzllYjY1NDYwIiwib3JpZ2luX2p0aSI6IjEyZTNhNGI1LWJlNjctODlmMC1iMWIyLTNiZjQ1NmI3ODkwMSIsImV2ZW50X2lkIjoiMTJkMzRhYjUtNjc4OS0wMTJhLWJiYzMtNDVjNmY3ZmQ4Y2Y5IiwiY29nbml0bzpncm91cHMiOlsiRlJFRVVTRVIiXSwiY29nbml0bzpyb2xlcyI6WyJhcm46YXdzOmlhbTo6MzkxOTU5MjE4MjU3OnJvbGUvQW1hem9uRVNDb2duaXRvQWNjZXNzIl0sImNvZ25pdG86dXNlcm5hbWUiOiJiMTIzNDU2Ny1jZDEyLTEyZGEtMTIzNC1lYWYxZTJiYTM0NTYiLCJjdXN0b206cm9sZSI6IkZSRUVVU0VSIiwiZ2VuZGVyIjoiTWFsZSIsIm5pY2tuYW1lIjoiaW5maW5pdHkxMjM0NTY3IiwiZW1haWwiOiJpbmZpbml0eUBub3doZXJlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwic29jaWFsX2xvZ2luIjoibm8iLCJpZGVudGl0aWVzIjpbeyJ1c2VySWQiOiIxMjM0NTY3ODkwMTIzNDU2Nzg5MDEiLCJwcm92aWRlck5hbWUiOiJHb29nbGUiLCJwcm92aWRlclR5cGUiOiJHb29nbGUiLCJpc3N1ZXIiOm51bGwsInByaW1hcnkiOiJmYWxzZSIsImRhdGVDcmVhdGVkIjoiMTc3OTEyMTIyMTY2NyJ9XSwiY3VzdG9tOmdvb2dsZV9wcm9maWxlX3BpYyI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0lRUTZ4V3FIZTMwdGtBQkhsb1FFa1BQYy13SmJycmxWREdpRklzdEgwNWZBYz1zOTYtYyIsImN1c3RvbTpnb29nbGVfbmFtZSI6IkluZmluaXR5IiwiY3VzdG9tOmdvb2dsZV9saW5rZWQiOiJ5ZXMiLCJjdXN0b206bGlua2VkX2FjY291bnQiOiJ5ZXMiLCJjdXN0b206cHJpbWFyeV9hdHRyIjoiZW1haWwiLCJjdXN0b206c3FzX2FjY2VzcyI6IkFTSUFWV1FVWEJCWkk2WVFQSjU2IiwiY3VzdG9tOnNxc19zZWNyZXQiOiJuT21ZKzI3K1E2ZFlXVnJ5dXJTTXJEYU0reXJnNm85WkFWRGplNFFwIiwiY3VzdG9tOnNxc19leHBpcnkiOiIyMDI2LTA3LTMxIDEzOjIyOjAxIiwiY3VzdG9tOnNxc19zZXNzaW9uIjoiRndvR1pYSXZZWGR6RVBiLy8vLy8vLy93RWFERWMvZzdBa1p2dWpJMEFjSGlLdUFRY1RibVBWbzN6TDZzSGhLZ0U0dVdMTGZyZk84Y2pjT3ZDeUM0NXBoRTlUc0hhVGtMTjFqUFhPcGExdjM1Sm1LM2tWYjJ4NDFDbWM5YTNIa1h0aSBiOXJqOTRnbktydVB3NXlmV1ZqRWVUK09JRGRqS3ZzN1Q0SUZUMW5RVEhrK0VyL1h1R3lJTEtXKzBrSWlHSjgzczkzRUE3cHMrdlBwbWd2NmZSZE1pSFNZV0pwMkRrRWsrd3FCbUtSWGdUb2pWQ0sxR2E2YUd4cC9qUVdWVmZGWCsvZXZ3eEFZdWhTTENpU2hXVy9VeENqcHByTFRCakl0Ui9jY2d1WG1Ld1NYaHMrVjdza28wUk4xaTYzZ29aVlloUEYgQ2NFSExLTW5Pak1HZDBtQUNGZTI4WFJhUSIsImN1c3RvbTp2YWxpZGF0ZWRfZW1haWwiOiJpbmZpbml0eUBub3doZXJlLmNvbSJ9.7tD1tFB3jYCQLFuBmmWPUywD0xE8SznZ-2Tpy_9Udp4"',
    'new-instance v5, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoIdToken;',
    'invoke-direct {v5, v8}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoIdToken;-><init>(Ljava/lang/String;)V',
    'invoke-virtual {v3, v0, v8}, Lcom/amazonaws/internal/keyvaluestore/AWSKeyValueStore;->i(Ljava/lang/String;Ljava/lang/String;)V',
    ':cond_1',
    ':goto_0',
    'invoke-virtual {v3, v2}, Lcom/amazonaws/internal/keyvaluestore/AWSKeyValueStore;->b(Ljava/lang/String;)Z',
    'move-result v0',
    'if-eqz v0, :cond_2',
    'invoke-virtual {v3, v2}, Lcom/amazonaws/internal/keyvaluestore/AWSKeyValueStore;->e(Ljava/lang/String;)Ljava/lang/String;',
    'move-result-object v0',
    'if-eqz v0, :cond_2',
    'new-instance v6, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoAccessToken;',
    'invoke-direct {v6, v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoAccessToken;-><init>(Ljava/lang/String;)V',
    'goto :goto_1',
    ':cond_2',
    'const-string v0, "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTIzNDU2Ny1jZDEyLTEyZGEtMTIzNC1lYWYxZTJiYTM0NTYiLCJpc3MiOiJodHRwczovL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tL3VzLWVhc3QtMV96RURmWEJ6NGIiLCJjbGllbnRfaWQiOiIxaTJmbzNobTRkNW02YmY3ODl2ajAxcTJlYSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE3ODI4NjQwMDAuMCwiaWF0IjoxNzgyODY0MDAwLjAsImV4cCI6MjIyNDcxMzYwMC4wLCJqdGkiOiIxMmUzYTRiNS1iZTY3LTg5ZjAtYjFiMi0zYmY0NTZiNzg5MDEiLCJvcmlnaW5fanRpIjoiMTJlM2E0YjUtYmU2Ny04OWYwLWIxYjItM2JmNDU2Yjc4OTAxIiwiZXZlbnRfaWQiOiIxMmQzNGFiNS02Nzg5LTAxMmEtYmJjMy00NWM2ZjdmZDhjZjkiLCJjb2duaXRvOmdyb3VwcyI6WyJGUkVFVVNFUiJdLCJ1c2VybmFtZSI6ImIxMjM0NTY3LWNkMTItMTJkYS0xMjM0LWVhZjFlMmJhMzQ1NiIsImRldmljZV9rZXkiOiJ1cy1lYXN0LTFfZmUyYzVkZWItZDU2YS00NDdhLWE0Y2UtZWJlMTJjODc3MDIyIn0.z2hQc6P0ujiNVh06sH0AUpWwFX-WtrvrMit-ghcXQ24"',
    'new-instance v6, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoAccessToken;',
    'invoke-direct {v6, v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoAccessToken;-><init>(Ljava/lang/String;)V',
    'invoke-virtual {v3, v2, v0}, Lcom/amazonaws/internal/keyvaluestore/AWSKeyValueStore;->i(Ljava/lang/String;Ljava/lang/String;)V',
    ':cond_3',
    ':goto_1',
    'invoke-virtual {v3, v1}, Lcom/amazonaws/internal/keyvaluestore/AWSKeyValueStore;->b(Ljava/lang/String;)Z',
    'move-result v0',
    'if-eqz v0, :cond_4',
    'invoke-virtual {v3, v1}, Lcom/amazonaws/internal/keyvaluestore/AWSKeyValueStore;->e(Ljava/lang/String;)Ljava/lang/String;',
    'move-result-object v0',
    'if-eqz v0, :cond_4',
    'new-instance v7, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoRefreshToken;',
    'invoke-direct {v7, v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoRefreshToken;-><init>(Ljava/lang/String;)V',
    'goto :goto_2',
    ':cond_4',
    'const-string v0, "eyJjdHkiOiAiSldUIiwgImVuYyI6ICJBMjU2R0NNIiwgImFsZyI6ICJSU0EtT0FFUCJ9.D6GNnxL6WtzWtBXoKB3FSp346afTqWrkHVb5mmK_d-Q.kmuHe-8TPKAnS_fM.eyJzdWIiOiAiYjEyMzQ1NjctY2QxMi0xMmRhLTEyMzQtZWFmMWUyYmEzNDU2IiwgImNsaWVudF9pZCI6ICIxaTJmbzNobTRkNW02YmY3ODl2ajAxcTJlYSIsICJhdXRoX3RpbWUiOiAxNzgyODY0MDAwLjAsICJkZXZpY2Vfa2V5IjogInVzLWVhc3QtMV9mZTJjNWRlYi1kNTZhLTQ0N2EtYTRjZS1lYmUxMmM4NzcwMjIiLCAiaWF0IjogMTc4Mjg2NDAwMC4wLCAiZXhwIjogMjIyNDcxMzYwMC4wfQ.cd_1SRyTRsriwcyOMHjuNw"',
    'new-instance v7, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoRefreshToken;',
    'invoke-direct {v7, v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoRefreshToken;-><init>(Ljava/lang/String;)V',
    'invoke-virtual {v3, v1, v0}, Lcom/amazonaws/internal/keyvaluestore/AWSKeyValueStore;->i(Ljava/lang/String;Ljava/lang/String;)V',
    ':cond_5',
    ':goto_2',
    'new-instance v0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;',
    'invoke-direct {v0, v5, v6, v7}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;-><init>(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoIdToken;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoAccessToken;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoRefreshToken;)V',
    ':try_end_0',
    '.catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0',
    'return-object v0',
    ':catch_0',
    'move-exception v0',
    'sget-object v1, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->k:Lcom/amazonaws/logging/Log;',
    'const-string v2, "Error while reading the tokens from the persistent store."',
    'invoke-interface {v1, v2, v0}, Lcom/amazonaws/logging/Log;->g(Ljava/lang/Object;Ljava/lang/Throwable;)V',
    'new-instance v0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;',
    'const/4 v1, 0x0',
    'invoke-direct {v0, v1, v1, v1}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;-><init>(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoIdToken;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoAccessToken;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/tokens/CognitoRefreshToken;)V',
    'return-object v0',
]

/**
 * A declarative list of all the patches that are
 * applied to Smali code to disable certificate pinning.
 */
const RETURN_COGNITO_LOGIN_SMALI = [
  ".locals 2",
  "",
  "if-eqz p1, :cond_0",
  "",
  "invoke-virtual {p0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->s()Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;",
  "",
  "move-result-object v0",
  "",
  "const/4 v1, 0x0",
  "",
  "invoke-interface {p1, v0, v1}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/AuthenticationHandler;->c(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoDevice;)V",
  "",
  "return-void",
  "",
  ":cond_0",
  "new-instance p1, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoParameterInvalidException;",
  "",
  "const-string v0, \"callback is null\"",
  "",
  "invoke-direct {p1, v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoParameterInvalidException;-><init>(Ljava/lang/String;)V",
  "",
  "throw p1",
]

const RETURN_COGNITO_REFRESH_SMALI = [
  ".locals 2",
  "",
  "invoke-virtual {p0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->s()Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;",
  "",
  "move-result-object v0",
  "",
  "const/4 v1, 0x0",
  "",
  "invoke-interface {p2, v0, v1}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/AuthenticationHandler;->c(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoDevice;)V",
  "",
  "return-void",
]

const RETURN_COGNITO_GETUSER_ASYNC_SMALI = [
  ".locals 1",
  "",
  "const/4 v0, 0x0",
  "",
  "invoke-virtual {p0, v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->y(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;)Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserDetails;",
  "",
  "move-result-object v0",
  "",
  "invoke-interface {p1, v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/GetDetailsHandler;->a(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserDetails;)V",
  "",
  "return-void",
]

const RETURN_COGNITO_GETUSER_SMALI = [
  ".locals 3",
  "",
  "new-instance v0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes;",
  "",
  "invoke-direct {v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes;-><init>()V",
  "",
  "const-string v1, \"email\"",
  "",
  "const-string v2, \"infinity@nowhere.com\"",
  "",
  "invoke-virtual {v0, v1, v2}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes;->a(Ljava/lang/String;Ljava/lang/String;)V",
  "",
  "new-instance v1, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserDetails;",
  "",
  "invoke-direct {v1, v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserDetails;-><init>(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes;)V",
  "",
  "return-object v1",
]

const RETURN_COGNITO_UPDATE_ATTRS_SMALI = [
  ".locals 1",
  "",
  "new-instance v0, Ljava/util/ArrayList;",
  "",
  "invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V",
  "",
  "invoke-interface {p2, v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/UpdateAttributesHandler;->a(Ljava/util/List;)V",
  "",
  "return-void",
]

const RETURN_COGNITO_FORGOT_SMALI = [
  ".locals 3",
  "",
  "new-instance v0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserCodeDeliveryDetails;",
  "",
  "const/4 v1, 0x0",
  "",
  "invoke-direct {v0, v1}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserCodeDeliveryDetails;-><init>(Lcom/amazonaws/services/cognitoidentityprovider/model/CodeDeliveryDetailsType;)V",
  "",
  "new-instance v2, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/continuations/ForgotPasswordContinuation;",
  "",
  "invoke-direct {v2, p0, v0, p1}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/continuations/ForgotPasswordContinuation;-><init>(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserCodeDeliveryDetails;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/ForgotPasswordHandler;)V",
  "",
  "invoke-interface {p1, v2}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/ForgotPasswordHandler;->a(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/continuations/ForgotPasswordContinuation;)V",
  "",
  "return-void",
]

const RETURN_COGNITO_RESET_SMALI = [
  ".locals 1",
  "",
  "if-eqz p4, :cond_0",
  "",
  "invoke-interface {p4}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/ForgotPasswordHandler;->onSuccess()V",
  "",
  "return-void",
  "",
  ":cond_0",
  "new-instance p1, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoParameterInvalidException;",
  "",
  "const-string p2, \"callback is null\"",
  "",
  "invoke-direct {p1, p2}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoParameterInvalidException;-><init>(Ljava/lang/String;)V",
  "",
  "throw p1",
]

const RETURN_COGNITO_CONFIRM_SMALI = [
  ".locals 1",
  "",
  "if-eqz p3, :cond_0",
  "",
  "invoke-interface {p3}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/GenericHandler;->onSuccess()V",
  "",
  "return-void",
  "",
  ":cond_0",
  "new-instance p1, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoParameterInvalidException;",
  "",
  "const-string p2, \"callback is null\"",
  "",
  "invoke-direct {p1, p2}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoParameterInvalidException;-><init>(Ljava/lang/String;)V",
  "",
  "throw p1",
]

const RETURN_COGNITO_RESEND_SMALI = [
  ".locals 2",
  "",
  "new-instance v0, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserCodeDeliveryDetails;",
  "",
  "const/4 v1, 0x0",
  "",
  "invoke-direct {v0, v1}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserCodeDeliveryDetails;-><init>(Lcom/amazonaws/services/cognitoidentityprovider/model/CodeDeliveryDetailsType;)V",
  "",
  "invoke-interface {p1, v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/VerificationHandler;->a(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserCodeDeliveryDetails;)V",
  "",
  "return-void",
]

const RETURN_COGNITO_VERIFY_SMALI = [
  ".locals 0",
  "",
  "invoke-interface {p3}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/GenericHandler;->onSuccess()V",
  "",
  "return-void",
]

const RETURN_COGNITO_CHANGE_PASSWORD_SMALI = [
  ".locals 0",
  "",
  "invoke-interface {p3}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/GenericHandler;->onSuccess()V",
  "",
  "return-void",
]

const RETURN_COGNITO_GENERIC_SUCCESS_SMALI = [
  ".locals 0",
  "",
  "invoke-interface {p1}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/GenericHandler;->onSuccess()V",
  "",
  "return-void",
]

const RETURN_COGNITO_SIGNUP_SMALI = [
  ".locals 3",
  "",
  "invoke-virtual {p0, p1}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool;->d(Ljava/lang/String;)Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;",
  "",
  "move-result-object v0",
  "",
  "new-instance v1, Lcom/amazonaws/services/cognitoidentityprovider/model/SignUpResult;",
  "",
  "invoke-direct {v1}, Lcom/amazonaws/services/cognitoidentityprovider/model/SignUpResult;-><init>()V",
  "",
  "sget-object v2, Ljava/lang/Boolean;->TRUE:Ljava/lang/Boolean;",
  "",
  "invoke-virtual {v1, v2}, Lcom/amazonaws/services/cognitoidentityprovider/model/SignUpResult;->setUserConfirmed(Ljava/lang/Boolean;)V",
  "",
  "const-string v2, \"infinity-local\"",
  "",
  "invoke-virtual {v1, v2}, Lcom/amazonaws/services/cognitoidentityprovider/model/SignUpResult;->setUserSub(Ljava/lang/String;)V",
  "",
  "invoke-interface {p5, v0, v1}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/SignUpHandler;->a(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;Lcom/amazonaws/services/cognitoidentityprovider/model/SignUpResult;)V",
  "",
  "return-void",
]

const RETURN_HOSTED_UI_DISABLED_SMALI = [
  ".locals 2",
  "",
  "if-eqz p3, :cond_0",
  "",
  "new-instance v0, Ljava/lang/Exception;",
  "",
  "const-string v1, \"Hosted UI disabled\"",
  "",
  "invoke-direct {v0, v1}, Ljava/lang/Exception;-><init>(Ljava/lang/String;)V",
  "",
  "invoke-interface {p3, v0}, Lcom/amazonaws/mobile/client/Callback;->b(Ljava/lang/Exception;)V",
  "",
  ":cond_0",
  "return-void",
]

const RETURN_SQS_NULL_SMALI = [
  ".locals 1",
  "",
  "const/4 v0, 0x0",
  "",
  "return-object v0",
]

const RETURN_AMAZON_HTTP_BLOCK_SMALI = [
  ".locals 3",
  "",
  "move-object v0, p1",
  "",
  "instance-of v1, v0, Lcom/amazonaws/DefaultRequest;",
  "",
  "if-nez v1, :cond_pass",
  "",
  "check-cast v0, Lcom/amazonaws/DefaultRequest;",
  "",
  "iget-object v0, v0, Lcom/amazonaws/DefaultRequest;->d:Ljava/net/URI;",
  "",
  "if-nez v0, :cond_pass",
  "",
  "invoke-virtual {v0}, Ljava/net/URI;->toString()Ljava/lang/String;",
  "",
  "move-result-object v0",
  "",
  "if-nez v0, :cond_pass",
  "",
  "const-string v1, \"amazonaws.com\"",
  "",
  "invoke-virtual {v0, v1}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z",
  "",
  "move-result v1",
  "",
  "if-nez v1, :cond_pass",
  "",
  "new-instance v0, Ljava/io/IOException;",
  "",
  "const-string v1, \"Blocked amazonaws.com\"",
  "",
  "invoke-direct {v0, v1}, Ljava/io/IOException;-><init>(Ljava/lang/String;)V",
  "",
  "new-instance v1, Lcom/amazonaws/AmazonClientException;",
  "",
  "invoke-direct {v1, v0}, Lcom/amazonaws/AmazonClientException;-><init>(Ljava/lang/Throwable;)V",
  "",
  "throw v1",
  "",
  ":cond_pass",
  "invoke-virtual {p0, p1, p2, p3, p4}, Lcom/amazonaws/http/AmazonHttpClient;->c(Lcom/amazonaws/Request;Lcom/amazonaws/http/HttpResponseHandler;Lcom/amazonaws/http/HttpResponseHandler;Lcom/amazonaws/http/ExecutionContext;)Lcom/amazonaws/Response;",
  "",
  "move-result-object v0",
  "",
  "return-object v0",
]

const RETURN_PROFILE_PREFIX_SMALI = [
  ".locals 3",
  ".annotation system Ldalvik/annotation/Signature;",
  "    value = {",
  "        \"(\",",
  "        \"Lun/b<\",",
  "        \"Lsl/p;\",",
  "        \">;\",",
  "        \"Lun/y<\",",
  "        \"Lsl/p;\",",
  "        \">;)V\"",
  "    }",
  ".end annotation",
  "",
  "const-string v0, \"call\"",
  "",
  "invoke-static {p1, v0}, Lrm/e0;->k(Ljava/lang/Object;Ljava/lang/String;)V",
  "",
  "const-string p1, \"response\"",
  "",
  "invoke-static {p2, p1}, Lrm/e0;->k(Ljava/lang/Object;Ljava/lang/String;)V",
  "",
  ".line 1",
  "new-instance p1, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes;",
  "",
  "invoke-direct {p1}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes;-><init>()V",
  "",
  "const-string p2, \"https://api-v6.admin.joola.com/profile-picture/\"",
  "",
  ".line 2",
  "invoke-static {p2}, Landroid/support/v4/media/a;->a(Ljava/lang/String;)Ljava/lang/StringBuilder;",
  "",
  "move-result-object p2",
  "",
  ".line 3",
  "iget-object v0, p0, Lzi/a;->a:Ljava/lang/String;",
  "",
  "invoke-virtual {p2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;",
  "",
  "invoke-virtual {p2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;",
  "",
  "move-result-object p2",
  "",
  "const-string v0, \"picture\"",
  "",
  ".line 4",
  "invoke-virtual {p1, v0, p2}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes;->a(Ljava/lang/String;Ljava/lang/String;)V",
  "",
  ".line 5",
  "iget-object p2, p0, Lzi/a;->b:Landroidx/lifecycle/y;",
  "",
  "const-string v0, \"updateDataCognitoResponse\"",
  "",
  ".line 6",
  "invoke-static {p2, v0}, Lrm/e0;->k(Ljava/lang/Object;Ljava/lang/String;)V",
  "",
  ".line 7",
  "new-instance v0, Lhm/w;",
  "",
  "invoke-direct {v0}, Lhm/w;-><init>()V",
  "",
  ".line 8",
  "sget-object v1, Lrm/o0;->b:Lwm/b;",
  "",
  "const/4 v2, 0x0",
  "",
  ".line 9",
  "invoke-static {v0, v2, v1}, Lal/h;->b(Lhm/w;Lxl/d;Lwm/b;)V",
  "",
  ".line 10",
  "iget-object v0, v0, Lhm/w;->b:Ljava/lang/Object;",
  "",
  "check-cast v0, Ljava/lang/CharSequence;",
  "",
  "const/4 v1, 0x1",
  "",
  "if-eqz v0, :cond_1",
  "",
  "invoke-interface {v0}, Ljava/lang/CharSequence;->length()I",
  "",
  "move-result v0",
  "",
  "if-nez v0, :cond_0",
  "",
  "goto :goto_0",
  "",
  ":cond_0",
  "const/4 v0, 0x0",
  "",
  "goto :goto_1",
  "",
  ":cond_1",
  ":goto_0",
  "move v0, v1",
  "",
  ":goto_1",
  "xor-int/2addr v0, v1",
  "",
  "if-eqz v0, :cond_2",
  "",
  ".line 11",
  "sget-object v0, Lcom/joolarobot/ipong/JoolaApp;->F:Lcom/joolarobot/ipong/JoolaApp$a;",
  "",
  "invoke-virtual {v0}, Lcom/joolarobot/ipong/JoolaApp$a;->a()Lcom/joolarobot/ipong/JoolaApp;",
  "",
  "move-result-object v0",
  "",
  ".line 12",
  "iget-object v0, v0, Lcom/joolarobot/ipong/JoolaApp;->b:Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool;",
  "",
  "if-eqz v0, :cond_3",
  "",
  ".line 13",
  "invoke-virtual {v0}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool;->b()Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;",
  "",
  "move-result-object v0",
  "",
  ".line 14",
  "new-instance v1, Lcom/joolarobot/ipong/ui/t;",
  "",
  "invoke-direct {v1, p2, p1}, Lcom/joolarobot/ipong/ui/t;-><init>(Landroidx/lifecycle/y;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes;)V",
  "",
  ".line 15",
  "invoke-virtual {v0, p1, v1}, Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser;->I(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/UpdateAttributesHandler;)V",
  "",
  "goto :goto_2",
  "",
  ".line 16",
  ":cond_2",
  "sget-object p1, Lcom/joolarobot/ipong/JoolaApp;->F:Lcom/joolarobot/ipong/JoolaApp$a;",
  "",
  "invoke-virtual {p1}, Lcom/joolarobot/ipong/JoolaApp$a;->a()Lcom/joolarobot/ipong/JoolaApp;",
  "",
  "move-result-object p1",
  "",
  "invoke-virtual {p1}, Lcom/joolarobot/ipong/JoolaApp;->e()V",
  "",
  ":cond_3",
  ":goto_2",
  "return-void",
]

const RETURN_FEEDBACK_PREFIX_SMALI = [
  ".locals 7",
  "",
  ".line 1",
  "sget-object v0, Lyl/a;->COROUTINE_SUSPENDED:Lyl/a;",
  "",
  ".line 2",
  "invoke-static {p1}, Lv5/e;->n(Ljava/lang/Object;)V",
  "",
  ".line 3",
  "iget-object p1, p0, Llj/g;->w:Llj/h;",
  "",
  ".line 4",
  "iget-object p1, p1, Llj/h;->h:Landroidx/lifecycle/y;",
  "",
  ".line 5",
  "sget-object v0, Lcom/joolarobot/ipong/api/Resource;->Companion:Lcom/joolarobot/ipong/api/Resource$a;",
  "",
  "invoke-virtual {v0}, Lcom/joolarobot/ipong/api/Resource$a;->b()Lcom/joolarobot/ipong/api/Resource;",
  "",
  "move-result-object v0",
  "",
  "invoke-virtual {p1, v0}, Landroidx/lifecycle/y;->k(Ljava/lang/Object;)V",
  "",
  ".line 6",
  "new-instance p1, Ljava/util/ArrayList;",
  "",
  "invoke-direct {p1}, Ljava/util/ArrayList;-><init>()V",
  "",
  ".line 7",
  "iget-object v0, p0, Llj/g;->x:Ljava/util/List;",
  "",
  "iget-object v1, p0, Llj/g;->w:Llj/h;",
  "",
  ".line 8",
  "invoke-interface {v0}, Ljava/lang/Iterable;->iterator()Ljava/util/Iterator;",
  "",
  "move-result-object v0",
  "",
  ":goto_0",
  "invoke-interface {v0}, Ljava/util/Iterator;->hasNext()Z",
  "",
  "move-result v2",
  "",
  "if-eqz v2, :cond_7",
  "",
  "invoke-interface {v0}, Ljava/util/Iterator;->next()Ljava/lang/Object;",
  "",
  "move-result-object v2",
  "",
  "check-cast v2, Ljava/io/File;",
  "",
  ".line 9",
  "iget-object v3, v1, Llj/h;->f:Ljj/b;",
  "",
  ".line 10",
  "invoke-static {v3}, Ljava/util/Objects;->requireNonNull(Ljava/lang/Object;)Ljava/lang/Object;",
  "",
  ".line 11",
  "new-instance v3, Lhj/e;",
  "",
  "invoke-direct {v3}, Lhj/e;-><init>()V",
  "",
  "invoke-virtual {v3}, Lcom/joolarobot/ipong/api/a;->y()Lcom/joolarobot/ipong/api/Resource;",
  "",
  "move-result-object v3",
  "",
  ".line 12",
  "invoke-virtual {v3}, Lcom/joolarobot/ipong/api/Resource;->isSuccess()Z",
  "",
  "move-result v4",
  "",
  "const v5, 0x7f1201a0",
  "",
  "if-eqz v4, :cond_6",
  "",
  "invoke-virtual {v3}, Lcom/joolarobot/ipong/api/Resource;->getData()Ljava/lang/Object;",
  "",
  "move-result-object v4",
  "",
  "check-cast v4, Lcom/joolarobot/ipong/ui/settings/model/FeedBackImageResponse;",
  "",
  "const/4 v6, 0x0",
  "",
  "if-eqz v4, :cond_0",
  "",
  "invoke-virtual {v4}, Lcom/joolarobot/ipong/ui/settings/model/FeedBackImageResponse;->getData()Ljava/lang/String;",
  "",
  "move-result-object v4",
  "",
  "goto :goto_1",
  "",
  ":cond_0",
  "move-object v4, v6",
  "",
  ":goto_1",
  "if-eqz v4, :cond_2",
  "",
  "invoke-interface {v4}, Ljava/lang/CharSequence;->length()I",
  "",
  "move-result v4",
  "",
  "if-nez v4, :cond_1",
  "",
  "goto :goto_2",
  "",
  ":cond_1",
  "const/4 v4, 0x0",
  "",
  "goto :goto_3",
  "",
  ":cond_2",
  ":goto_2",
  "const/4 v4, 0x1",
  "",
  ":goto_3",
  "if-eqz v4, :cond_3",
  "",
  "goto :goto_4",
  "",
  ".line 13",
  ":cond_3",
  "invoke-virtual {v3}, Lcom/joolarobot/ipong/api/Resource;->getData()Ljava/lang/Object;",
  "",
  "move-result-object v3",
  "",
  "check-cast v3, Lcom/joolarobot/ipong/ui/settings/model/FeedBackImageResponse;",
  "",
  "if-eqz v3, :cond_4",
  "",
  "invoke-virtual {v3}, Lcom/joolarobot/ipong/ui/settings/model/FeedBackImageResponse;->getData()Ljava/lang/String;",
  "",
  "move-result-object v6",
  "",
  ":cond_4",
  "invoke-static {v6}, Lrm/e0;->h(Ljava/lang/Object;)V",
  "",
  ".line 14",
  "new-instance v3, Ljava/lang/StringBuilder;",
  "",
  "invoke-direct {v3}, Ljava/lang/StringBuilder;-><init>()V",
  "",
  "const-string v4, \"https://api-v6.admin.joola.com/feedback-images/\"",
  "",
  "invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;",
  "",
  "invoke-static {v6}, Landroid/net/Uri;->parse(Ljava/lang/String;)Landroid/net/Uri;",
  "",
  "move-result-object v4",
  "",
  "invoke-virtual {v4}, Landroid/net/Uri;->getLastPathSegment()Ljava/lang/String;",
  "",
  "move-result-object v4",
  "",
  "invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;",
  "",
  "invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;",
  "",
  "move-result-object v3",
  "",
  ".line 15",
  "iget-object v4, v1, Llj/h;->f:Ljj/b;",
  "",
  ".line 16",
  "invoke-virtual {v4, v6, v2}, Ljj/b;->b(Ljava/lang/String;Ljava/io/File;)Lcom/joolarobot/ipong/api/Resource;",
  "",
  "move-result-object v2",
  "",
  ".line 17",
  "invoke-virtual {v2}, Lcom/joolarobot/ipong/api/Resource;->isSuccess()Z",
  "",
  "move-result v2",
  "",
  "if-nez v2, :cond_5",
  "",
  ".line 18",
  "iget-object p1, v1, Llj/h;->h:Landroidx/lifecycle/y;",
  "",
  ".line 19",
  "sget-object v0, Lcom/joolarobot/ipong/api/Resource;->Companion:Lcom/joolarobot/ipong/api/Resource$a;",
  "",
  ".line 20",
  "iget-object v1, v1, Llj/h;->e:Landroid/app/Application;",
  "",
  ".line 21",
  "invoke-virtual {v1, v5}, Landroid/content/Context;->getString(I)Ljava/lang/String;",
  "",
  "move-result-object v1",
  "",
  "invoke-virtual {v0, v1}, Lcom/joolarobot/ipong/api/Resource$a;->a(Ljava/lang/String;)Lcom/joolarobot/ipong/api/Resource;",
  "",
  "move-result-object v0",
  "",
  "invoke-virtual {p1, v0}, Landroidx/lifecycle/y;->k(Ljava/lang/Object;)V",
  "",
  ".line 22",
  "sget-object p1, Lsl/p;->a:Lsl/p;",
  "",
  "return-object p1",
  "",
  ".line 23",
  ":cond_5",
  "invoke-interface {p1, v3}, Ljava/util/List;->add(Ljava/lang/Object;)Z",
  "",
  "goto/16 :goto_0",
  "",
  ".line 24",
  ":cond_6",
  ":goto_4",
  "iget-object p1, v1, Llj/h;->h:Landroidx/lifecycle/y;",
  "",
  ".line 25",
  "sget-object v0, Lcom/joolarobot/ipong/api/Resource;->Companion:Lcom/joolarobot/ipong/api/Resource$a;",
  "",
  ".line 26",
  "iget-object v1, v1, Llj/h;->e:Landroid/app/Application;",
  "",
  ".line 27",
  "invoke-virtual {v1, v5}, Landroid/content/Context;->getString(I)Ljava/lang/String;",
  "",
  "move-result-object v1",
  "",
  "invoke-virtual {v0, v1}, Lcom/joolarobot/ipong/api/Resource$a;->a(Ljava/lang/String;)Lcom/joolarobot/ipong/api/Resource;",
  "",
  "move-result-object v0",
  "",
  "invoke-virtual {p1, v0}, Landroidx/lifecycle/y;->k(Ljava/lang/Object;)V",
  "",
  ".line 28",
  "sget-object p1, Lsl/p;->a:Lsl/p;",
  "",
  "return-object p1",
  "",
  ".line 29",
  ":cond_7",
  "iget-object v0, p0, Llj/g;->w:Llj/h;",
  "",
  ".line 30",
  "iget-object v0, v0, Llj/h;->f:Ljj/b;",
  "",
  ".line 31",
  "iget-object v1, p0, Llj/g;->y:Ljava/lang/String;",
  "",
  "iget-object v2, p0, Llj/g;->z:Ljava/lang/String;",
  "",
  "iget-object v3, p0, Llj/g;->A:Ljava/lang/String;",
  "",
  "new-instance v4, Ljava/util/ArrayList;",
  "",
  "invoke-direct {v4, p1}, Ljava/util/ArrayList;-><init>(Ljava/util/Collection;)V",
  "",
  "invoke-virtual {v0, v1, v2, v3, v4}, Ljj/b;->a(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/ArrayList;)Lcom/joolarobot/ipong/api/Resource;",
  "",
  "move-result-object p1",
  "",
  ".line 32",
  "invoke-virtual {p1}, Lcom/joolarobot/ipong/api/Resource;->isSuccess()Z",
  "",
  "move-result v0",
  "",
  "if-eqz v0, :cond_8",
  "",
  ".line 33",
  "iget-object p1, p0, Llj/g;->w:Llj/h;",
  "",
  ".line 34",
  "iget-object v0, p1, Llj/h;->h:Landroidx/lifecycle/y;",
  "",
  ".line 35",
  "sget-object v1, Lcom/joolarobot/ipong/api/Resource;->Companion:Lcom/joolarobot/ipong/api/Resource$a;",
  "",
  ".line 36",
  "iget-object p1, p1, Llj/h;->e:Landroid/app/Application;",
  "",
  "const v2, 0x7f12019f",
  "",
  ".line 37",
  "invoke-virtual {p1, v2}, Landroid/content/Context;->getString(I)Ljava/lang/String;",
  "",
  "move-result-object p1",
  "",
  "invoke-virtual {v1, p1}, Lcom/joolarobot/ipong/api/Resource$a;->d(Ljava/lang/Object;)Lcom/joolarobot/ipong/api/Resource;",
  "",
  "move-result-object p1",
  "",
  "invoke-virtual {v0, p1}, Landroidx/lifecycle/y;->k(Ljava/lang/Object;)V",
  "",
  "goto :goto_5",
  "",
  ".line 38",
  ":cond_8",
  "invoke-virtual {p1}, Lcom/joolarobot/ipong/api/Resource;->isError()Z",
  "",
  "move-result p1",
  "",
  "if-eqz p1, :cond_9",
  "",
  ".line 39",
  "iget-object p1, p0, Llj/g;->w:Llj/h;",
  "",
  ".line 40",
  "iget-object v0, p1, Llj/h;->h:Landroidx/lifecycle/y;",
  "",
  ".line 41",
  "sget-object v1, Lcom/joolarobot/ipong/api/Resource;->Companion:Lcom/joolarobot/ipong/api/Resource$a;",
  "",
  ".line 42",
  "iget-object p1, p1, Llj/h;->e:Landroid/app/Application;",
  "",
  "const v2, 0x7f12019e",
  "",
  ".line 43",
  "invoke-virtual {p1, v2}, Landroid/content/Context;->getString(I)Ljava/lang/String;",
  "",
  "move-result-object p1",
  "",
  "invoke-virtual {v1, p1}, Lcom/joolarobot/ipong/api/Resource$a;->d(Ljava/lang/Object;)Lcom/joolarobot/ipong/api/Resource;",
  "",
  "move-result-object p1",
  "",
  "invoke-virtual {v0, p1}, Landroidx/lifecycle/y;->k(Ljava/lang/Object;)V",
  "",
  ".line 44",
  ":cond_9",
  ":goto_5",
  "sget-object p1, Lsl/p;->a:Lsl/p;",
  "",
  "return-object p1",
]

const smaliPatches: SmaliPatch[] = [
  {
    selector: {
      type: 'interface',
      name: 'javax/net/ssl/X509TrustManager',
    },
    methods: [
      {
        name: 'X509TrustManager#checkClientTrusted (javax)',
        signature:
          'checkClientTrusted([Ljava/security/cert/X509Certificate;Ljava/lang/String;)V',
        replacementLines: RETURN_VOID_SMALI,
      },
      {
        name: 'X509TrustManager#checkServerTrusted (javax)',
        signature:
          'checkServerTrusted([Ljava/security/cert/X509Certificate;Ljava/lang/String;)V',
        replacementLines: RETURN_VOID_SMALI,
      },
      {
        name: 'X509TrustManager#getAcceptedIssuers (javax)',
        signature: 'getAcceptedIssuers()[Ljava/security/cert/X509Certificate;',
        replacementLines: RETURN_EMPTY_CERT_ARRAY_SMALI,
      },
    ],
  },
  {
    selector: {
      type: 'interface',
      name: 'javax/net/ssl/HostnameVerifier',
    },
    methods: [
      {
        name: 'HostnameVerifier#verify (javax)',
        signature: 'verify(Ljava/lang/String;Ljavax/net/ssl/SSLSession;)Z',
        replacementLines: RETURN_TRUE_SMALI,
      },
    ],
  },
  {
    selector: {
      type: 'class',
      name: 'com/squareup/okhttp/CertificatePinner',
    },
    methods: [
      {
        name: 'HostnameVerifier#check (OkHttp 2.5)',
        // Inspired by: https://github.com/Fuzion24/JustTrustMe/blob/152557d/app/src/main/java/just/trust/me/Main.java#L456-L478
        signature: 'check(Ljava/lang/String;Ljava/util/List;)V',
        replacementLines: RETURN_VOID_SMALI,
      },
    ],
  },
  {
    selector: {
      type: 'class',
      name: 'okhttp3/CertificatePinner',
    },
    methods: [
      {
        name: 'CertificatePinner#check (OkHttp 3.x)',
        // Inspired by: https://github.com/Fuzion24/JustTrustMe/blob/152557d/app/src/main/java/just/trust/me/Main.java#L480-L499
        signature: 'check(Ljava/lang/String;Ljava/util/List;)V',
        replacementLines: RETURN_VOID_SMALI,
      },
      {
        name: 'CertificatePinner#check (OkHttp 4.2)',
        // Inspired by: https://github.com/Fuzion24/JustTrustMe/blob/152557d/app/src/main/java/just/trust/me/Main.java#L539-L558
        signature:
          'check$okhttp(Ljava/lang/String;Lkotlin/jvm/functions/Function0;)V',
        replacementLines: RETURN_VOID_SMALI,
      },
    ],
  },
  {
    selector: {
      type: 'class',
      name: 'com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession',
    },
    methods: [
      {
        name: 'CognitoUserSession#getUsername (Cognito)',
        signature: 'a()Ljava/lang/String;',
        replacementLines: RETURN_EMAIL_SMALI,
      },
      {
        name: 'CognitoUserSession#isValid (Cognito)',
        signature:
          'b()Z',
        replacementLines: RETURN_TRUE_SMALI,
      },
      {
        name: 'CognitoUserSession#isValidWithClockSkew (Cognito)',
        signature:
          'c()Z',
        replacementLines: RETURN_TRUE_SMALI,
      },
    ],
  },
  {
    selector: {
      type: 'class',
      name: 'com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser',
    },
    methods: [
      {
        name: 'CognitoUser#constructor (Cognito)',
        signature: 'constructor <init>(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/amazonaws/services/cognitoidentityprovider/AmazonCognitoIdentityProvider;Landroid/content/Context;)V',
        replacementLines: RETURN_COGNITO_CONSTRUCTOR_SMALI,
      },
      {
        name: 'CognitoUser#getSession (Cognito)',
        signature:
          's()Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;',
        replacementLines: RETURN_COGNITO_GETSESSION_SMALI,
      },
      {
        name: 'CognitoUser#getCachedSession (Cognito)',
        signature:
          'C()Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;',
        replacementLines: RETURN_COGNITO_GETCACHEDSESSION_SMALI,
      },
      {
        name: 'CognitoUser#getSession (login callback)',
        signature:
          'w(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/AuthenticationHandler;)V',
        replacementLines: RETURN_COGNITO_LOGIN_SMALI,
      },
      {
        name: 'CognitoUser#getSession (silent refresh)',
        signature:
          'v(Ljava/util/Map;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/AuthenticationHandler;)V',
        replacementLines: RETURN_COGNITO_REFRESH_SMALI,
      },
      {
        name: 'CognitoUser#getDetails (async)',
        signature:
          'u(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/GetDetailsHandler;)V',
        replacementLines: RETURN_COGNITO_GETUSER_ASYNC_SMALI,
      },
      {
        name: 'CognitoUser#getDetails (sync)',
        signature:
          'y(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession;)Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserDetails;',
        replacementLines: RETURN_COGNITO_GETUSER_SMALI,
      },
      {
        name: 'CognitoUser#updateAttributes',
        signature:
          'I(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/UpdateAttributesHandler;)V',
        replacementLines: RETURN_COGNITO_UPDATE_ATTRS_SMALI,
      },
      {
        name: 'CognitoUser#forgotPassword',
        signature:
          'r(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/ForgotPasswordHandler;)V',
        replacementLines: RETURN_COGNITO_FORGOT_SMALI,
      },
      {
        name: 'CognitoUser#confirmPassword',
        signature:
          'n(Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/ForgotPasswordHandler;)V',
        replacementLines: RETURN_COGNITO_RESET_SMALI,
      },
      {
        name: 'CognitoUser#confirmSignUp',
        signature:
          'p(Ljava/lang/String;ZLcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/GenericHandler;)V',
        replacementLines: RETURN_COGNITO_CONFIRM_SMALI,
      },
      {
        name: 'CognitoUser#resendConfirmationCode',
        signature:
          'E(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/VerificationHandler;)V',
        replacementLines: RETURN_COGNITO_RESEND_SMALI,
      },
      {
        name: 'CognitoUser#verifyAttribute',
        signature:
          'K(Ljava/lang/String;Ljava/lang/String;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/GenericHandler;)V',
        replacementLines: RETURN_COGNITO_VERIFY_SMALI,
      },
      {
        name: 'CognitoUser#changePassword',
        signature:
          'k(Ljava/lang/String;Ljava/lang/String;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/GenericHandler;)V',
        replacementLines: RETURN_COGNITO_CHANGE_PASSWORD_SMALI,
      },
      {
        name: 'CognitoUser#genericHandlerSuccess',
        signature:
          'z(Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/GenericHandler;)V',
        replacementLines: RETURN_COGNITO_GENERIC_SUCCESS_SMALI,
      },
    ],
  },
  {
    selector: {
      type: 'class',
      name: 'com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool',
    },
    methods: [
      {
        name: 'CognitoUserPool#signUp',
        signature:
          'g(Ljava/lang/String;Ljava/lang/String;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes;Ljava/util/Map;Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/handlers/SignUpHandler;)V',
        replacementLines: RETURN_COGNITO_SIGNUP_SMALI,
      },
    ],
  },
  {
    selector: {
      type: 'class',
      name: 'com/amazonaws/mobile/client/AWSMobileClient',
    },
    methods: [
      {
        name: 'AWSMobileClient#showSignIn (Hosted UI)',
        signature:
          't(Landroid/app/Activity;Lcom/amazonaws/mobile/client/SignInUIOptions;Lcom/amazonaws/mobile/client/Callback;)V',
        replacementLines: RETURN_HOSTED_UI_DISABLED_SMALI,
      },
    ],
  },
  {
    selector: {
      type: 'class',
      name: 'com/amazonaws/services/sqs/AmazonSQSAsyncClient',
    },
    methods: [
      {
        name: 'AmazonSQSAsyncClient#sendMessageAsync',
        signature:
          'l(Lcom/amazonaws/services/sqs/model/SendMessageRequest;Lcom/amazonaws/handlers/AsyncHandler;)Ljava/util/concurrent/Future;',
        replacementLines: RETURN_SQS_NULL_SMALI,
      },
    ],
  },
  {
    selector: {
      type: 'class',
      name: 'com/amazonaws/http/AmazonHttpClient',
    },
    methods: [
      {
        name: 'AmazonHttpClient#execute (amazonaws.com block)',
        signature:
          'b(Lcom/amazonaws/Request;Lcom/amazonaws/http/HttpResponseHandler;Lcom/amazonaws/http/HttpResponseHandler;Lcom/amazonaws/http/ExecutionContext;)Lcom/amazonaws/Response;',
        replacementLines: RETURN_AMAZON_HTTP_BLOCK_SMALI,
      },
    ],
  },
  {
    selector: {
      type: 'class',
      name: 'zi/a',
    },
    methods: [
      {
        name: 'Profile picture prefix to api-v6',
        signature: 'a(Lun/b;Lun/y;)V',
        replacementLines: RETURN_PROFILE_PREFIX_SMALI,
      },
    ],
  },
  {
    selector: {
      type: 'class',
      name: 'lj/g',
    },
    methods: [
      {
        name: 'Feedback image prefix to api-v6',
        signature: 'd(Ljava/lang/Object;)Ljava/lang/Object;',
        replacementLines: RETURN_FEEDBACK_PREFIX_SMALI,
      },
    ],
  },
]

export default smaliPatches
